export const imageStatements = [
    "A giant squid attacking a pirate ship",
    "A cat riding a unicorn",
    "A person with a pineapple for a head",
    "A dog wearing a top hat and monocle",
    "A mermaid sunbathing on a rock",
    "A dragon flying through a city skyline",
    "A person with tentacles for arms",
    "A ghost haunting an old mansion",
    "A dinosaur in a modern city",
    "A robot riding a bicycle",
    "A vampire drinking a milkshake",
    "A werewolf howling at the moon",
    "A person with butterfly wings",
    "A zombie apocalypse",
    "A ninja fighting a giant spider",
    "A person with a snake for a tongue",
    "A witch casting a spell",
    "A person with a cloud for a head",
    "A cyborg fighting a giant robot",
    "A person with a cactus for a body",
    "A sea monster attacking a ship",
    "A person with a bird's nest for hair",
    "A person with a crystal for a heart",
    "A person with a mushroom for a hat",
    "A giant mushroom taking over a city",
    "A person with a squid for a face",
    "A person with a tree growing out of their head",
    "A person with a flamingo for a leg",
    "A person with a pineapple for a body",
    "A person with a rainbow for hair",
    "A person with a jellyfish for a head",
    "A person with a galaxy for a face",
    "A person with a shark for a hand",
    "A person with a snowman for a head",
    "A person with a sunflower for a face",
    "A person with a waterfall for hair",
    "A person with a dragonfly for wings",
    "A person with a peacock for a tail",
    "A person with a phoenix for a head",
    "A person with a spider web for a face",
    "A person with a starry sky for a body",
    "A person with a unicorn horn",
    "A person with an octopus for a hat",
    "A person with antlers",
    "A person with fairy wings",
    "A person with horns and wings",
    "A person with robotic arms",
    "A person with tentacles for hair",
    "A person with wings made of fire",
    "A person with a dragon tail",
    "A person with a fox tail",
    "A person with a rabbit tail",
    "A person with a wolf tail",
    "A person with a dragon for a pet",
    "A person with a giant robot for a pet",
    "A person with a unicorn for a pet",
    "A person with a magical creature as a companion"
  ];
  